name: lint

on:
  push:
    branches: [main]
  pull_request:

env:
  GOLANGCI_LINT_VERSION: v2.12.2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Check that 'go mod tidy' was called before commit
        run: go mod tidy -diff
      - uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
